baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
# theme = 'ananke'

[outputs]
home = ["HTML", "JSON"]

[params]
custom_index = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true